// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFrHfHuKjrz0eJtQoz4l65XQFWigI7GLQ',
    appId: '1:153171715536:web:fde462374f03fa29f045d5',
    messagingSenderId: '153171715536',
    projectId: 'login-flutter-1a710',
    authDomain: 'login-flutter-1a710.firebaseapp.com',
    storageBucket: 'login-flutter-1a710.firebasestorage.app',
    measurementId: 'G-2MZ0VB6J2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoRSxg0Jbtpt5tGUV8mq9IPMqNHQ9LN40',
    appId: '1:153171715536:android:9c01bcc786240617f045d5',
    messagingSenderId: '153171715536',
    projectId: 'login-flutter-1a710',
    storageBucket: 'login-flutter-1a710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7kGDPwx1ut0Q0iVOvlySMzQOaih0Re1o',
    appId: '1:153171715536:ios:a3d08c0b73b53fcbf045d5',
    messagingSenderId: '153171715536',
    projectId: 'login-flutter-1a710',
    storageBucket: 'login-flutter-1a710.firebasestorage.app',
    androidClientId:
        '153171715536-ml6c9k3bnvt2ut9vruelvk4lgd96u0ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.joyin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7kGDPwx1ut0Q0iVOvlySMzQOaih0Re1o',
    appId: '1:153171715536:ios:a3d08c0b73b53fcbf045d5',
    messagingSenderId: '153171715536',
    projectId: 'login-flutter-1a710',
    storageBucket: 'login-flutter-1a710.firebasestorage.app',
    androidClientId:
        '153171715536-ml6c9k3bnvt2ut9vruelvk4lgd96u0ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.joyin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFrHfHuKjrz0eJtQoz4l65XQFWigI7GLQ',
    appId: '1:153171715536:web:0e39b68ba8317f0cf045d5',
    messagingSenderId: '153171715536',
    projectId: 'login-flutter-1a710',
    authDomain: 'login-flutter-1a710.firebaseapp.com',
    storageBucket: 'login-flutter-1a710.firebasestorage.app',
    measurementId: 'G-8STGV9Q73P',
  );
}
